# Site settings
course_name: The Boring Data Science
course_description: "Coruse Site for The Boring Data Science"
course_semester: "2025"

baseurl: "/The-Boring-Data-Science" # the subpath of your site, e.g. /blog/
url: "http://nabin2004.github.io/" # the base hostname & protocol for your site

schoolname: "Nabin"
schoolurl: "https://olinabin.com.np/"
twitter_username: nabintwts

address: |
    Kathmandu
    Nepal

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
